# .scrutinizer.yml

build:

  dependencies:
    before:
      - rm composer.lock

  tests:
    override:
      -
        command: 'phpdbg -qrr vendor/bin/phpunit --coverage-clover tests/build/clover.xml'
        coverage:
          file: 'tests/build/clover.xml'
          format: 'clover'
      - php-scrutinizer-run

  nodes:

    php73:
      environment:
        php: 7.3

    php74:
      environment:
        php: 7.4

    php80:
      environment:
        php: 8.0

    php81:
      environment:
        php: 8.1


checks:
  php: true


filter:
  excluded_paths:
    - tests/*
